version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soka_app
    volumes:
      - ./soka_db:/var/lib/mysql
    ports:
      - "3306:3306"
  back:
    build: ./back
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./back:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - db
    tty: true
  front:
    build: ./front
    command: npm start
    volumes:
      - ./front:/app
    ports: 
      - ${FRONT_PORT}:3000
    depends_on: 
      - back
    tty: true
volumes:
  soka_db:
